---
title: "Code Map"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Code_map}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse) 
library(visNetwork)

```


```{r code relations, echo = FALSE, eval = TRUE, warning= FALSE}

network <- readRDS("./network.rds")

#### Build network widget ####

visNetwork(network[[2]], network[[1]], width = "100%", height = "1000") %>%      # Build the network
  #visLayout(randomSeed = 10) %>%                                          # Control the randomisation of the layout
  visHierarchicalLayout(direction = "UD") %>%                             # Control the randomisation of the layout
  visLegend(width = 0.15) %>%                                             # Add a legend
  visOptions(highlightNearest = list(enabled = TRUE, labelOnly = FALSE),  # Control the highlighting when you select a script
             nodesIdSelection = TRUE) %>%                                 # Allow the user to select a script from a drop down list
  visGroups(groupname = "bathymetry", shape = "dot", color = list(background = "#440154FF", border = "#440154FF", # Control colouring and highlighting per group
                                                                highlight = list(background = "white", border = "#440154FF"))) %>%
  visGroups(groupname = "NM", shape = "dot",color = list(background = "#46337EFF", border = "#46337EFF",
                                                         highlight = list(background = "white", border = "#46337EFF"))) %>% 
  visGroups(groupname = "atmosphere", shape = "dot", color = list(background = "#365C8DFF", border = "#365C8DFF",
                                                                  highlight = list(background = "white", border = "#365C8DFF"))) %>% 
  visGroups(groupname = "flows", shape = "dot", color = list(background = "#1FA187FF", border = "#1FA187FF",
                                                             highlight = list(background = "white", border = "#1FA187FF"))) %>% 
  visGroups(groupname = "gfw", shape = "dot",color = list(background = "#277F8EFF", border = "#277F8EFF",
                                                          highlight = list(background = "white", border = "#277F8EFF"))) %>% 
  visGroups(groupname = "ices", shape = "dot",color = list(background = "#4AC16DFF", border = "#4AC16DFF",
                                                           highlight = list(background = "white", border = "#4AC16DFF"))) %>% 
  visGroups(groupname = "sediment", shape = "dot", color = list(background = "#9FDA3AFF", border = "#9FDA3AFF",
                                                                highlight = list(background = "white", border = "#9FDA3AFF"))) %>% 
  visGroups(groupname = "strathE2E", shape = "dot", color = list(background = "#FDE725FF", border = "#FDE725FF",
                                                                 highlight = list(background = "white", border = "#FDE725FF")))

```  

