---
title: "Data Sources"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data_Sources}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<style>
div.description { background-color:#FFCC33; border-radius: 20px; padding: 10px;}
</style>

Introductory text

# Ecological Drivers

## EMEP

<div class = "description"> Atmospheric deposition of reduced and oxidised Nitrogen from a model. </div>

## EMCWF

<div class = "description"> Significant wave height and direction. </div>

## GEBCO

<div class = "description"> Global bathymetry model. </div>

## Globcolour

<div class = "description"> Suspended particulate matter from satellite colour data. </div>

## NEMO-MEDUSA

### Driving data

<div class = "description"> Driving data **FOR** NEMO-MEDUSA includes surface irradiance and air temperature at the sea surface. </div>

### Outputs

<div class = "description"> NEMO-MEDUSA model **outputs** extracted for StrathE2EPolar include:
Water temperature,
DIN,
Blah, </div>

## NGU

<div class = "description"> Sediment classes in the Barents Sea, overview document. </div>


#### <i class="fa fa-globe" aria-hidden="true" style ="color:#003399;"></i>  Spatial extent

Barents Sea. 


#### <i class="fa fa-stopwatch" aria-hidden="true" style ="color:#003399;"></i>  Temporal extent

Snapshot


#### <i class="fa fa-folder" aria-hidden="true" style ="color:#003399;"></i>  File structure

* 1 shape file.
* 8mb total memory requirement.
* The file contains a collection of spatial polygons where sediment classes are expected to occur within the Barents Sea.


#### <i class="fa fa-eye" aria-hidden="true" style ="color:#FFCC33;"></i>  Target variable

* "SEDKORNSTR", Sediment grain size code.
* "SEDKO_NAVN" , Sediment grain size class name.
 

#### <i class="fa fa-layer-group" aria-hidden="true" style ="color:#FFCC33;"></i>  Spatial variables

Polygon boundaries embedded in shapefile.


#### <i class="fa fa-plus" aria-hidden="true" style ="color:#FFCC33;"></i>  Other variables

NA

<br><br>


## SINMOD

<div class = "description"> Tidally resolved water velocity fields in the Arctic. </div>


#### <i class="fa fa-globe" aria-hidden="true" style ="color:#003399;"></i>  Spatial extent

Arctic. 


#### <i class="fa fa-stopwatch" aria-hidden="true" style ="color:#003399;"></i>  Temporal extent

* *From* 2003/01/01. 
* *To* 2018/12/28.
* *In* 336 timesteps (every 2 hours in a 28 day month).
* *Duration* 16 years.


#### <i class="fa fa-folder" aria-hidden="true" style ="color:#003399;"></i>  File structure

* 191 netcdf files.
* 600gb total memory requirement.
* 1 netcdf file contains a 3D spatial grid and all timesteps within a month.


#### <i class="fa fa-eye" aria-hidden="true" style ="color:#FFCC33;"></i>  Target variables

* "u_east", Zonal veolcity.
* "v_north", Meridional velocity.


#### <i class="fa fa-layer-group" aria-hidden="true" style ="color:#FFCC33;"></i>  Spatial variables

* "gridLats", matrix of latitudes (curvilinear grid).
* "gridLons", matrix of longitudes (curvilinear grid).
* "depths", matrix of depths.
* "ldepths", vector of depth layer thicknesses?


#### <i class="fa fa-plus" aria-hidden="true" style ="color:#FFCC33;"></i>  Other variables

"w_east", "w_north", "w_velocity", "vertical_diffusivity", "NO3", "PhytoF", "PhytoD", "temperature",
"salinity", "ice_thickness", "ice_compactness", "freezing_rate", "salinity_ice", "uIce_east", "vIce_north", "uUnderIceE",           "vUnderIceN", "elevation".

<br><br>

# Fishing Fleet

## Global Fishing Watch

<div class = "description"> Fishing effort from anonymised VMS signals and a model of vessel movement patterns. </div>


#### <i class="fa fa-globe" aria-hidden="true" style ="color:#003399;"></i>  Spatial extent

Global. 


#### <i class="fa fa-stopwatch" aria-hidden="true" style ="color:#003399;"></i>  Temporal extent

* *From* 2012/01/01. 
* *To* 2016/12/31.
* *In* days.
* *Duration* 5 years.


#### <i class="fa fa-folder" aria-hidden="true" style ="color:#003399;"></i>  File structure

* 1,827 csv files.
* 18gb total memory requirement.
* 1 csv file contains a list of pixels from the global grid where fishing was detected for a day.


#### <i class="fa fa-eye" aria-hidden="true" style ="color:#FFCC33;"></i>  Target variables

* "geartype", fishing gear used.
* "fishing_hours", total hours of fishing within a pixel for a given day).


#### <i class="fa fa-layer-group" aria-hidden="true" style ="color:#FFCC33;"></i>  Spatial variables

* "lat_bin", latitude * 100.
* "lon_bin", longitude * 100


#### <i class="fa fa-plus" aria-hidden="true" style ="color:#FFCC33;"></i>  Other variables

"flag", "vessel_hours", "mmsi_present".

<br>

## ICES

<div class = "description"> Fisheries landings by species and country. </div>

# Target data

## Blanchard report
